name: LoveApp CI

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  python-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: loveapp

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pyright

      - name: Lint with flake8
        run: |
          flake8 \
            --max-line-length=120 \
            --ignore=E501

      - name: Type-check with pyright
        run: |
          pyright 